### ISSUE TITLE
Support for SQL

### ISSUE THREAD

**Issue by tedypranolo** [karyfoundation/comment-vscode#1]
Can we also get support for sql?

**Comment by pmkary** [comment]
Hello @tedypranolo the answer is: "Of course!" and it's already added. The thing is VS Code has no API to get the configuration of the current language so we keep a tiny dictionary to know which language has which inline comment style. If you wanted any other language just ping us and I'll increment the dictionary... :D

**Comment by tedypranolo** [comment]
Thank you @pmkary . That was fast! I'll look forward to the vs marketplace version.
